name: local
variables:
  - name: base_url
    value: http://localhost:8010
  - name: employee_field_id
    value: 6d4ba23d-00dd-42a0-a2da-ce9afcf8aa0c
  - name: entity_id
    value: 7efb264a-53d2-4fc2-8824-d04dbf1408e4
  - name: group_id
    value: 862609cd-2c5c-4f61-b451-478c9f252341
  - name: benefit_id
    value: d9f4251c-9eeb-41ec-8548-17e2fb26f17c
  - name: policy_id
    value: a8897ca3-d21d-466d-b92f-fde3d9fef439
  - name: employee_id
    value: 57fe294d-036d-4d60-a47f-4e4e2a96feba
  - name: auth_token
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3Zjk0NTc2Ni0yNGVlLTQzZDMtYWNiMi0zNTYyODUyN2YwOTIiLCJwZXJzb25hIjoiY29ycG9yYXRlX2FkbWluIiwiZW1wIjoiNTdmZTI5NGQtMDM2ZC00ZDYwLWE0N2YtNGU0ZTJhOTZmZWJhIiwib3JnIjoiNDVlZGQxOTYtYTVmZi00ZjVmLTg0OTAtYWQ5ZTUyYWU3YjViIiwicmVzdHJpY3RlZCI6ZmFsc2UsInR5cCI6ImFjY2VzcyIsImp0aSI6IjNiZTgxMzQyLTc1M2MtNDA5YS04Njc2LTA5Mjg5NTlmZjE1YiIsImlhdCI6MTc4Nzk4Nzg4MCwiZXhwIjoxNzg3OTg4NzgwfQ.1-sKzI2VcDlM3CDQVzS8maYEKJmi_FvY8Vcrq6pRb8g
  - name: org_id
    value: 45edd196-a5ff-4f5f-8490-ad9e52ae7b5b
  - name: handoff_secret
    value: ""
  - name: vehicle_id
    value: 1d1e3b85-ad37-4ac3-8f82-debbcf486a12
  - name: file_id
    value: c3d90483-0a65-4886-91a4-4c072f4ff16e
  - name: driver_id
    value: e2934f95-38e4-4e54-9f14-f7c064a09480
  - secret: true
    name: auth_token
