name: staging
variables:
  - name: base_url
    value: https://benefits-staging.chronon.co.in
  - name: employee_field_id
    value: 0f3a066c-901f-4c9d-a4ce-48e27ca5c224
  - name: entity_id
    value: f0cffe85-5e5a-4cbe-b319-694c6f84b957
  - name: employee_id
    value: 6501ea66-222c-428a-adb8-d497911eefb7
  - name: benefit_id
    value: c87c3a57-cd71-4e9b-9bea-754a5485daef
  - name: group_id
    value: 3ba44929-06ec-4f7d-815d-153199ad3f15
  - name: policy_id
    value: 812a6f6e-57d5-45a2-8e10-405825800e7f
  - name: org_id
    value: 966f6b4c-582d-48c4-b856-629a8279e59b
  - name: handoff_secret
    value: pinehandoffsecret
  - name: auth_token
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzVlMmIxMS0wYzU5LTRiZDgtODg1Ny00ZTc5YjZkM2I4Y2YiLCJwZXJzb25hIjoiY29ycG9yYXRlX2FkbWluIiwiZW1wIjoiMDBlNGYzMGUtZDUyNC00MTM2LTg4NGYtOWNkMjVmYWQ2NDJmIiwib3JnIjoiNTA1YTM4NDMtODhhMC00NmU3LTg1NjYtODU4ZDY2NjJkMDAzIiwicmVzdHJpY3RlZCI6ZmFsc2UsInR5cCI6ImFjY2VzcyIsImp0aSI6ImYyODcwMmI2LWE4YTMtNDYxZi05ODg4LTE0YzRlNWRhMTdlNiIsImlhdCI6MTc4OTU4NjUwOCwiZXhwIjoxNzg5NTg3NDA4fQ.16QbvZFq5a3zWDuC9pL8Nem2yhSMD4rTlFLic_MC--Q
