name: staging
variables:
  - name: base_url
    value: https://benefits-staging.chronon.co.in
  - name: employee_field_id
    value: a25b82be-5b94-4613-af51-40b3b1430bf6
  - name: entity_id
    value: f0cffe85-5e5a-4cbe-b319-694c6f84b957
  - name: employee_id
    value: 6501ea66-222c-428a-adb8-d497911eefb7
  - name: benefit_id
    value: c87c3a57-cd71-4e9b-9bea-754a5485daef
  - name: group_id
    value: 3ba44929-06ec-4f7d-815d-153199ad3f15
  - name: policy_id
    value: e3a66ba3-1ce2-44f2-b006-6ea9434eeff0
  - name: auth_token
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhODU3NDcxMC04Y2VkLTQ5YjctYjU3Ni05OGI3YjEyNjNjYzAiLCJwZXJzb25hIjoiY29ycG9yYXRlX2FkbWluIiwiZW1wIjoiZWFkODc5NjktOTViMS00OGJmLTk4N2QtOWUzYzkwMGQ3NmE5Iiwib3JnIjoiNTA1YTM4NDMtODhhMC00NmU3LTg1NjYtODU4ZDY2NjJkMDAzIiwicmVzdHJpY3RlZCI6ZmFsc2UsInR5cCI6ImFjY2VzcyIsImp0aSI6ImFjYzcxMDM4LTA3MTYtNDJiMS04N2MyLWMyZWM4M2VmMjVjOCIsImlhdCI6MTc4NzUwMTQ4MSwiZXhwIjoxNzg3NTAyMzgxfQ.GNObMAPYKeKpbvKBzVnaQwLfDncSYxqiSCYXZqnkeUs
  - name: org_id
    value: 505a3843-88a0-46e7-8566-858d6662d003
  - name: handoff_secret
    value: pinehandoffsecret
